### ISSUE TITLE
MC 1.16.5; WorldEdit 7.2.3: Chest item drop problem.

### ISSUE THREAD

**Issue by Spaex** [EngineHub/WorldEdit#1690]
**Versions**

WorldEdit version:
[22:02:37 INFO]: WorldEdit version 7.2.2
[22:02:37 INFO]: https://github.com/EngineHub/WorldEdit/
[22:02:37 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(7.2.2+fc3c499)

[22:02:37 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

Platform version: Paper version git-Paper-472 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Describe the bug**
When a filled chest get replaced (//set; Overwritten with Schematics by //paste) by WorldEdit the items drop to the ground. On version before (7.2.2) everything works fine and the Chest gets removed properly with all its contains.

**To Reproduce**
1. Place a Double Chest with some stuff inside
2. Mark it with the Selection Tool
3. use //set 0
4. The contains of the chest will drop to the ground

**Expected behavior**
The items should be removed like the chest instead of being dropped to the ground.

**Comment by wizjany** [comment]
#1686

**Comment by Brokkonaut** [comment]
It still happens in the latest snapshot

> we version
[23:50:31 INFO]: WorldEdit-Version 7.3.0-SNAPSHOT
[23:50:31 INFO]: https://github.com/EngineHub/WorldEdit/
[23:50:31 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(7.3.0-SNAPSHOT+5678-913d4d6)

[23:50:31 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**Comment by octylFractal** [comment]
bugs are fixed in 7.2.x branch, not master. we could eventually merge it to master, but it's not a priority.

**Comment by Brokkonaut** [comment]
Yes, merging would be great. I generally use the master branch on my test server to check for incompatibilities with my plugins.. And its a bit confusing when those bugs that are thought to be fixed still occur..
